min-players: 8
refill-chest-time: 600
deathmatch-time: 600
warmup-time: 30
supply-drop-time: 10
chest-loot:
  tier-1:
    - stone, 6
  tier-2:
    - coal, 4
  tier-3:
    - iron_ingot, 3
  tier-4:
    - gold_ingot, 2
  tier-5:
    - diamond, 1
breakable-blocks:
  - oak_leaves
placeable-blocks:
  - cake
supply-drop-content:
  - diamond_sword, 1
  - diamond, 4
  - diamond_leggings, 1
  - diamond_chestplate, 1
  - diamond_boots, 1
  - diamond_helmet, 1
  - iron_sword, 1
  - gold_apple, 3
  - ender_pearl, 2
  - compass, 1
llama-content:
  - apple, 8
  - diamond, 1
  - iron_ingot, 2
  - gold_ingot, 3
  - cooked_beef, 4
  - bread, 6
  - ender_pear, 1
  - gold_apple, 1